### ISSUE TITLE
(FIXED) Saving/creating blog posts doesn't work

### ISSUE THREAD

**Issue by robiso** [StephanStanisic/plugin-simpleblog#1]
@StephanStanisic first of all kudos for the great work on this plugin. 🚀 

**Bug description**
When trying to create a new post with WonderCMS installed in a subfolder, the incorrect path is called when trying to post, returning in a 404 response:
Request URL: https://www.domain.com/plugins/simpleblog/new.php
should be
Request URL:https://www.domain.com/wcms-installe ... og/new.php

There's a similar bug when trying to save content inside a blog post.

Not entirely sure if this has to do something with the "slug" function.

To reproduce this, simply put WonderCMS in a subfolder and try creating a blog post or editing an already created one.

**Comment by robiso** [comment]
Please check latest changes made to WonderCMS 3.0.0 experimental, which will make it easier to provide some of the fixes:
https://github.com/robiso/wondercms/commit/a06d546192a55aa1a9d1c70f523fd8f31cc86cc6
We added a rootURL contstant in the main javascript function. So plugins can now always get the correct path even with PHP (for example) with the url function.
`$script = <<<EOT
        <script src="{$Wcms->url('plugins/additional-contents/js/script.js')}" type="text/javascript"></script>
EOT;`

Previously, you couldn't have gotten the correct path, now you can with the following changes and saving will work on subfolders.

In your blog.js https://github.com/StephanStanisic/plugin-simpleblog/blob/master/js/blog.js
add the following for the paths:
`$.post( rootURL + "/plugins/simpleblog/save.php", { key: key, value: value, page: page })`
and
`$.post( rootURL + "/plugins/simpleblog/new.php", { page: name })`

I would also add the slugify function for the following:
```
$key = $Wcms->slugify($_POST["key"]);
$page = $Wcms->slugify($_POST["page"]);
```
and possibly also add htmlspecialchars in the new.php
`    "title" => htmlspecialchars($_POST['page'], ENT_QUOTES),`

**Comment by StephanStanisic** [comment]
Good work! Completely forgot about the `$Wcms->slugify()` function. 

Closing this issue as this is fixed.
