### ISSUE TITLE
Database gets reset after update

### ISSUE THREAD

**Issue by robiso** [StephanStanisic/plugin-simpleblog#13]
### As reported by Turboblack:
- when an admin updates the plugin via the WonderCMS theme/plugin updater, the database gets reset/deleted.

### Reason
- WonderCMS updater works in a way that (when updating) a plugin folder gets completely removed and replaced with all files from master branch (via ZIP).

### Possible solutions
1. We either have to move the plugin database outside the actual plugin folder.
2. Change the updater.
3. Remove simpleblog.json in the repo and initiate the database when plugin is first installed and database doesn't already exist.
- we would need to somehow save the DB in memory when updating, and restore it after the update is done.

**Comment by robiso** [comment]
This has been fixed with the latest simple blog plugin version (simpleblog.json databse now moved to data folder to prevent it from being deleted).

Closing issue.

**Comment by StephanStanisic** [comment]
Hey @robiso, didn't see this issue.

The simpleblog.json gets generated on first start, so removing from the repo would also have worked.
But, I do think that the data folder is a more suitable place for the database.

Awesome work 🚀!

**Comment by robiso** [comment]
@StephanStanisic no problem.

Actually the issue would still persist for the following reason:
- the wcms updater removes the whole theme/plugin folder
  - this is why we moved the database to the data folder, so it never gets deleted.

We've had cases in the past where a plugin file was vulnerable and had to be removed from the users server.
Loving the plugin! 🚀
