### ISSUE TITLE
Additional security - add token verification.

### ISSUE THREAD

**Issue by robiso** [StephanStanisic/plugin-simpleblog#2]
Currently we only check if the user is logged in. 

I suggest adding a token check as an additional measure. This is to prevent phishing an admin by sending him a shortened url that would redirect him to creating a post https://www.domain.com/plugins/simpleblog/new.php?page=creatingPagesForAdminWithoutHimKnowing

WonderCMS always uses this for any sort of additional checks (on top of checking if the admin is logged in):
```
$this->loggedIn
&& $_SESSION['token'] === $_POST['token']
&& $this->hashVerify($_POST['token']))
```

The token is always saved in the a token variable (through JS).

And for including the token in the form:
`<input type="hidden" name="token" value="' . $this->getToken() . '">`

**Comment by StephanStanisic** [comment]
I had seen the token functions but didn't know how to implement these, so I didn't.
Will see if I can implement this.

**Comment by StephanStanisic** [comment]
Have added the token using the global javascript token variable.

**Comment by robiso** [comment]
Amazing work and nice fixes @StephanStanisic 👍
